name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build and test
        run: |
          # Lägg till kommandon för att bygga och testa applikationen här

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/marvinhalabi/karl
          username: marvinhalabi
          password: Yyn5KiJez6S2e2P

      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
