name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag my-image:latest ghcr.io/${{ github.repository_owner }}/my-image:latest

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${{ github.repository_owner }}/my-image:latest
