name: CI - Pull Request

on:
  pull_request:
    branches:
      - 'dev/*' # Matches any branch starting with 'dev/'
      - main

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      # Add additional steps as needed for your testing process
