name: Docker Image and GitHub Packages

on:
  push:
    branches:
      - 'dev/*' # Matches any branch starting with 'dev/'
    tags:
      - 'v*' # Matches any tag starting with 'v'

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.ref }}
        if: startsWith(github.ref, 'refs/tags/v')
